In [1]:
# Importing important Libraries
import pandas as pd
import mysql.connector

## Importing the dataset

In [5]:
df = pd.read_csv("J:\project\healthcare\Healtcare-Dataset.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Chandra Shekar\AppData\Local\Temp\ipykernel_25512\3643064495.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv("J:\project\healthcare\Healtcare-Dataset.csv")

,Patient_ID,Admit_Date,Discharge_Date,Diagnosis,Bed_Occupancy,Test,Doctor,Followup Date,Feedback,Billing Amount,Health Insurance Amount
0,23571,12/31/2022,1/12/2023,Viral Infection,General,MRI,Jay Sinha,1/20/2023,5.0,13234,11911
1,27781,1/4/2023,1/12/2023,Typhoid,ICU,MRI,Jaya Yaadav,1/16/2023,4.0,12241,11017
2,24413,1/5/2023,1/12/2023,Malaria,General,CT Scan,Jay Sinha,1/15/2023,5.0,35255,31730
3,27360,1/5/2023,1/12/2023,Flu,Private,X-Ray,Jaya Yaadav,1/19/2023,5.0,6582,5924
4,26097,1/6/2023,1/12/2023,Viral Infection,General,Blood Test,Jaya Yaadav,2/6/2023,4.9,4567,4110

## Data cleaning and preprocessing

In [6]:
# Checking if we have NULL values in the data or not
df.isnull().sum().any()

True

In [7]:
# True means that NULL values are present in the dataset

In [8]:
# Getting the column wise sum of NULL Values
df.isnull().sum()

Patient_ID                   0
Admit_Date                   0
Discharge_Date               0
Diagnosis                    0
Bed_Occupancy                0
Test                         0
Doctor                       0
Followup Date              122
Feedback                     0
Billing Amount               0
Health Insurance Amount      0
dtype: int64

In [9]:
# 122 rows of the Followup Date column have NULL values in the dataset

In [10]:
# Getting an idea about the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7157 entries, 0 to 7156
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               7157 non-null   int64
 1   Admit_Date               7157 non-null   object
 2   Discharge_Date           7157 non-null   object
 3   Diagnosis                7157 non-null   object
 4   Bed_Occupancy            7157 non-null   object
 5   Test                     7157 non-null   object
 6   Doctor                   7157 non-null   object
 7   Followup Date            7035 non-null   object
 8   Feedback                 7157 non-null   float64
 9   Billing Amount           7157 non-null   int64
 10  Health Insurance Amount  7157 non-null   int64
dtypes: float64(1), int64(3), object(7)
memory usage: 615.2+ KB

In [11]:
# Converting the "Billing Amount" column to float datatype
df['Billing Amount'] = df['Billing Amount'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7157 entries, 0 to 7156
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               7157 non-null   int64
 1   Admit_Date               7157 non-null   object
 2   Discharge_Date           7157 non-null   object
 3   Diagnosis                7157 non-null   object
 4   Bed_Occupancy            7157 non-null   object
 5   Test                     7157 non-null   object
 6   Doctor                   7157 non-null   object
 7   Followup Date            7035 non-null   object
 8   Feedback                 7157 non-null   float64
 9   Billing Amount           7157 non-null   float64
 10  Health Insurance Amount  7157 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 615.2+ KB

In [12]:
# Check for duplicate rows in the DataFrame
duplicates = df[df.duplicated()]

# Display the duplicate rows
print(duplicates)

Empty DataFrame
Columns: [Patient_ID, Admit_Date, Discharge_Date, Diagnosis, Bed_Occupancy, Test, Doctor, Followup Date, Feedback, Billing Amount, Health Insurance Amount]
Index: []

In [13]:
# The data does not contain any duplicate rows

In [14]:
# Dropping rows with NULL Values
df1=df.dropna(how='any')
df1

,Patient_ID,Admit_Date,Discharge_Date,Diagnosis,Bed_Occupancy,Test,Doctor,Followup Date,Feedback,Billing Amount,Health Insurance Amount
0,23571,12/31/2022,1/12/2023,Viral Infection,General,MRI,Jay Sinha,1/20/2023,5.0,13234.0,11911
1,27781,1/4/2023,1/12/2023,Typhoid,ICU,MRI,Jaya Yaadav,1/16/2023,4.0,12241.0,11017
2,24413,1/5/2023,1/12/2023,Malaria,General,CT Scan,Jay Sinha,1/15/2023,5.0,35255.0,31730
3,27360,1/5/2023,1/12/2023,Flu,Private,X-Ray,Jaya Yaadav,1/19/2023,5.0,6582.0,5924
4,26097,1/6/2023,1/12/2023,Viral Infection,General,Blood Test,Jaya Yaadav,2/6/2023,4.9,4567.0,4110
...,...,...,...,...,...,...,...,...,...,...,...
7151,28622,3/2/2024,3/7/2024,Flu,General,X-Ray,Ravi D,3/11/2024,4.0,6784.0,6106
7152,29885,3/3/2024,3/7/2024,Typhoid,Private,Blood Test,Jay Sinha,3/10/2024,5.0,2342.0,2108
7153,26517,3/4/2024,3/7/2024,Pneumonia,Private,CT Scan,Jaya Yaadav,3/14/2024,5.0,24943.0,22449
7155,24833,3/6/2024,3/7/2024,Typhoid,Private,X-Ray,Mark Joy,3/15/2024,4.9,3475.0,3128
7156,30727,3/6/2024,3/7/2024,Viral Infection,Private,Ultrasound,Jaya Yaadav,3/11/2024,5.0,66537.0,59883

In [15]:
# Checking if we have NULL values in the data or not
df1.isnull().sum().any()

False

In [16]:
# False means NULL values are not present in the dataset

In [17]:
# Getting the column wise sum of NULL values
df1.isnull().sum()

Patient_ID                 0
Admit_Date                 0
Discharge_Date             0
Diagnosis                  0
Bed_Occupancy              0
Test                       0
Doctor                     0
Followup Date              0
Feedback                   0
Billing Amount             0
Health Insurance Amount    0
dtype: int64

In [18]:
# Checking the datatype
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7035 entries, 0 to 7156
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               7035 non-null   int64
 1   Admit_Date               7035 non-null   object
 2   Discharge_Date           7035 non-null   object
 3   Diagnosis                7035 non-null   object
 4   Bed_Occupancy            7035 non-null   object
 5   Test                     7035 non-null   object
 6   Doctor                   7035 non-null   object
 7   Followup Date            7035 non-null   object
 8   Feedback                 7035 non-null   float64
 9   Billing Amount           7035 non-null   float64
 10  Health Insurance Amount  7035 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 659.5+ KB

## Creating Python SQL Connection

In [23]:
mydb = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '12345678',
    database = 'healthcare',
    autocommit = True
)

In [13]:
mydb

In [14]:
# Creating the cursor
mycursor = mydb.cursor()

In [15]:
# Checking the list of databases
mycursor.execute("Show Databases")
for i in mycursor:
    print(i)

('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [17]:
# Creating the Database
mycursor.execute('CREATE DATABASE Healthcare')

1

In [18]:
# Checking if database is created or not
mycursor.execute("Show Databases")
for i in mycursor:
    print(i)

('healthcare',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [19]:
mycursor.execute("USE Healthcare")

0

In [20]:
# Create the table

mycursor.execute('''CREATE TABLE healthcare_data (
    Patient_ID INT,
    Admit_Date DATETIME,
    Discharge_Date DATETIME,
    Diagnosis VARCHAR(50),
    Bed_Occupancy VARCHAR(50),
    Test VARCHAR(50),
    Doctor VARCHAR(50),
    `Followup Date` DATETIME,
    Feedback FLOAT,
    `Billing Amount` FLOAT,
    `Health Insurance Amount` FLOAT,
    PRIMARY KEY (Patient_ID)
)''')

0

In [21]:
# Inserting the data into the table

def data_to_sql(df, table_name):
    from sqlalchemy import create_engine  # Import create_engine
    from urllib.parse import quote_plus   # Import quote_plus to handle special characters in password

    # Properly encode the password if it contains special characters
    password = quote_plus('root')
    database_url = f'mysql+pymysql://root:{password}@localhost:3306/healthcare'
    
    # Create the engine
    engine = create_engine(database_url)
    
    # Insert the DataFrame into the specified table
    df.to_sql(name=table_name, con=engine, if_exists='append', index=False)
    
    # Dispose the engine
    engine.dispose()

In [22]:
# Calling the function
data_to_sql(df1, 'healthcare_data')